const sampleListings = [
  {
    title: "Cozy Beachside Bungalow",
    description: "A perfect getaway with all modern amenities.",
    image: {
      filename: "ListingImage",
      url: "https://images.unsplash.com/photo-1560347876-aeef00ee58a1",
    },
    price: 3994,
    location: "Jaipur",
    country: "India",
  },
  {
    title: "Modern City Loft",
    description: "Located in the heart of the city, ideal for explorers.",
    image: {
      filename: "ListingImage",
      url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
    },
    price: 4638,
    location: "Manali",
    country: "India",
  },
  {
    title: "Charming Countryside Cottage",
    description: "Surrounded by nature, with serene views and fresh air.",
    image: {
      filename: "ListingImage",
      url: "https://images.unsplash.com/photo-1570129477492-45c003edd2be",
    },
    price: 7975,
    location: "Chennai",
    country: "India",
  },
  {
    title: "Luxury Mountain Retreat",
    description: "Luxurious stay with panoramic mountain views.",
    image: {
      filename: "ListingImage",
      url: "https://images.unsplash.com/photo-1506744038136-46273834b3fb",
    },
    price: 2193,
    location: "Kolkata",
    country: "India",
  },
  {
    title: "Rustic Cabin in the Woods",
    description: "A cozy place for nature lovers.",
    image: {
      filename: "ListingImage",
      url: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914",
    },
    price: 1730,
    location: "Kolkata",
    country: "India",
  },
  {
    title: "Urban Studio Apartment",
    description: "Compact yet fully equipped, perfect for solo travelers.",
    image: {
      filename: "ListingImage",
      url: "https://images.unsplash.com/photo-1494526585095-c41746248156",
    },
    price: 5971,
    location: "Manali",
    country: "India",
  },
  {
    title: "Lakefront Treehouse",
    description: "Unwind with stunning lake views and cozy interiors.",
    image: {
      filename: "ListingImage",
      url: "https://images.unsplash.com/photo-1597262975002-c5c3b14bbd62",
    },
    price: 6247,
    location: "Shimla",
    country: "India",
  },
  {
    title: "Minimalist Desert Home",
    description: "Minimal design, maximum comfort.",
    image: {
      filename: "ListingImage",
      url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2",
    },
    price: 7490,
    location: "Udaipur",
    country: "India",
  },
  {
    title: "Historic Downtown Flat",
    description: "Walkable to top attractions and public transport.",
    image: {
      filename: "ListingImage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85",
    },
    price: 8345,
    location: "Mumbai",
    country: "India",
  },
  {
    title: "Secluded Island Villa",
    description: "Private beach access and modern furnishings.",
    image: {
      filename: "ListingImage",
      url: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb",
    },
    price: 5143,
    location: "Goa",
    country: "India",
  },
  {
    title: "Elegant Garden Apartment",
    description: "Peaceful garden views with elegant interiors.",
    image: {
      filename: "ListingImage",
      url: "https://images.unsplash.com/photo-1505691938895-1758d7feb511",
    },
    price: 5796,
    location: "New Delhi",
    country: "India",
  },
  {
    title: "Bohemian Chic Loft",
    description: "Colorful decor and a lively vibe.",
    image: {
      filename: "ListingImage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470",
    },
    price: 3821,
    location: "Jaipur",
    country: "India",
  },
  {
    title: "Classic Victorian House",
    description: "Classic charm meets modern amenities.",
    image: {
      filename: "ListingImage",
      url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
    },
    price: 3535,
    location: "Chennai",
    country: "India",
  },
  {
    title: "Sunny Seaside Condo",
    description: "Steps away from the beach with sunny vibes.",
    image: {
      filename: "ListingImage",
      url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
    },
    price: 3488,
    location: "Goa",
    country: "India",
  },
  {
    title: "Contemporary Glass House",
    description: "Architectural gem with floor-to-ceiling windows.",
    image: {
      filename: "ListingImage",
      url: "https://images.unsplash.com/photo-1599423300746-b62533397364",
    },
    price: 9983,
    location: "Shimla",
    country: "India",
  },
  {
    title: "Tropical Jungle Hideaway",
    description: "Hidden gem in the tropics, peaceful and private.",
    image: {
      filename: "ListingImage",
      url: "https://images.unsplash.com/photo-1519681393784-d120267933ba",
    },
    price: 7063,
    location: "Udaipur",
    country: "India",
  },
  {
    title: "Peaceful River Cabin",
    description: "Rustic charm with river views.",
    image: {
      filename: "ListingImage",
      url: "https://images.unsplash.com/photo-1531973968078-9bb02785f13d",
    },
    price: 7961,
    location: "Kolkata",
    country: "India",
  },
  {
    title: "Snowy Chalet Escape",
    description: "Perfect winter getaway with a fireplace.",
    image: {
      filename: "ListingImage",
      url: "https://images.unsplash.com/photo-1482192596544-9eb780fc7f66",
    },
    price: 8027,
    location: "Manali",
    country: "India",
  },
  {
    title: "Hipster Warehouse Loft",
    description: "Trendy space in a vibrant neighborhood.",
    image: {
      filename: "ListingImage",
      url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
    },
    price: 9162,
    location: "Mumbai",
    country: "India",
  },
  {
    title: "Spacious Family Home",
    description: "Great for families, fully stocked kitchen.",
    image: {
      filename: "ListingImage",
      url: "https://images.unsplash.com/photo-1528909514045-2fa4ac7a08ba",
    },
    price: 9643,
    location: "New Delhi",
    country: "India",
  },
  {
    title: "Tranquil Farm Stay",
    description: "Reconnect with nature in this charming farm stay.",
    image: {
      filename: "ListingImage",
      url: "https://images.unsplash.com/photo-1523217582562-09d0def993a6",
    },
    price: 3688,
    location: "Rishikesh",
    country: "India",
  },
  {
    title: "Romantic Parisian Studio",
    description: "Experience Parisian charm at its best.",
    image: {
      filename: "ListingImage",
      url: "https://images.unsplash.com/photo-1470770841072-f978cf4d019e",
    },
    price: 3971,
    location: "Udaipur",
    country: "India",
  },
  {
    title: "Lakeside A-Frame",
    description: "Iconic A-frame design by the lake.",
    image: {
      filename: "ListingImage",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e ",
    },
    price: 8074,
    location: "Rishikesh",
    country: "India",
  },
  {
    title: "Stylish Suburban Retreat",
    description: "Quiet neighborhood with stylish interiors.",
    image: {
      filename: "ListingImage",
      url: "https://images.unsplash.com/photo-1469474968028-56623f02e42e",
    },
    price: 2752,
    location: "New Delhi",
    country: "India",
  },
  {
    title: "Countryside Windmill Home",
    description: "Unique windmill experience in the countryside.",
    image: {
      filename: "ListingImage",
      url: "https://images.unsplash.com/photo-1502005097973-6a7082348e28",
    },
    price: 2186,
    location: "Chennai",
    country: "India",
  },
  {
    title: "Cliffside Ocean View",
    description: "Dramatic ocean views from the cliffside.",
    image: {
      filename: "ListingImage",
      url: "https://images.unsplash.com/photo-1506744038136-46273834b3fb",
    },
    price: 7857,
    location: "Goa",
    country: "India",
  },
  {
    title: "Modern Tiny House",
    description: "Tiny home living done right.",
    image: {
      filename: "ListingImage",
      url: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb",
    },
    price: 2361,
    location: "Mumbai",
    country: "India",
  },
  {
    title: "Historic Castle Room",
    description: "Sleep in history and wake up refreshed.",
    image: {
      filename: "ListingImage",
      url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
    },
    price: 6476,
    location: "Jaipur",
    country: "India",
  },
  {
    title: "Desert Dome Glamping",
    description: "Glamorous desert escape under the stars.",
    image: {
      filename: "ListingImage",
      url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2",
    },
    price: 3015,
    location: "Rishikesh",
    country: "India",
  },
  {
    title: "Woodland Hobbit House",
    description: "Whimsical and cozy woodland retreat.",
    image: {
      filename: "ListingImage",
      url: "https://images.unsplash.com/photo-1568605114967-8130f3a36994",
    },
    price: 9187,
    location: "Shimla",
    country: "India",
  },
];

module.exports = { data: sampleListings };
